name: 'Flow Status Action'
description: 'Delivery flow status check action'
author: 'zezaeoh <zezaeoh@github.com>'
inputs:
  application:
    required: true
    description: 'application name that registered in ops-monster'
  flow:
    required: true
    description: 'available flow: staging, production'
runs:
  using: 'node12'
  main: 'dist/index.js'
